### ISSUE TITLE
Cannot set default if no "default" file exists

### ISSUE THREAD

**Issue by yodaldevoid** [dopsi/console-tdm#22]
I tried to set a default session, but every time I did it exited out complaining about "No default session found" without setting the session I had specified as the default.

**Comment by gabm** [comment]
I have the same problem unfortunately...

**Comment by dopsi** [comment]
Should be fixed now, I'll publish a new release in a few days, once the other issues are closed.

**Comment by dopsi** [comment]
Fixed in bc11fd2

**Comment by gabm** [comment]
Well I'm afraid its still not working somehow:

```
~> tdmctl default extra/sway
tdmctl error: extra/sway is not available
~> tdmctl check extra/sway
/usr/bin/sway
```

Although it seems another problem maybe?

**Comment by gabm** [comment]
works great! thanks!
